#!/bin/sh

set -eu

root="$(dirname "$(realpath "$0")")"

os=$("$root/.cross-platform/.identify")
if [ -z "$os" ]; then
    >&2 echo "Error: unknown operating system"
    exit 1
fi

bin_path="$HOME/.local/bin"
mkdir -p "$bin_path"
for command in "$root/.cross-platform/"*; do
    command_name=$(basename "$command")
    cp "$command/$os" "$bin_path/$command_name"
done

source_profile_path="$root/.profile"
target_profile_path="$HOME/.profile"

if [ -e "target_profile_path" ]; then
    profile_backups_path="$HOME/.profile-backups"
    mkdir -p "$profile_backups_path"

    profile_backup_path="$profile_backups_path/$(date '+%Y_%m_%d-%H_%M_%S')"
    mv "$target_profile_path" "$profile_backup_path"

    echo "Backed up overwritten .profile in $profile_backup_path"
fi
cp "$source_profile_path" "$target_profile_path"

profiled_path="$HOME/.profile.d"
mkdir -p "$profiled_path"
cp "$root/.cross-platform/.profiled-path/$os" "$profiled_path/path"
