#!/bin/sh

set -eu

root="$(dirname "$(realpath "$0")")"

cross_platform_path="$root/.cross-platform"

os=$("$cross_platform_path/identify")
if [ -z "$os" ]; then
    >&2 echo "Error: unknown operating system"
    exit 1
fi

bin_path="$HOME/.local/bin"
mkdir -p "$bin_path"
for command in "$cross_platform_path/bin/"*; do
    command_name=$(basename "$command")
    cp "$command/$os" "$bin_path/$command_name"
done

source_profile_path="$root/.profile"
target_profile_path="$HOME/.profile"

if [ -e "target_profile_path" ]; then
    profile_backups_path="$HOME/.profile-backups"
    mkdir -p "$profile_backups_path"

    profile_backup_path="$profile_backups_path/$(date '+%Y_%m_%d-%H_%M_%S')"
    mv "$target_profile_path" "$profile_backup_path"

    echo "Backed up overwritten .profile in $profile_backup_path"
fi
cp "$source_profile_path" "$target_profile_path"

profiled_path="$HOME/.profile.d"
mkdir -p "$profiled_path"

profiled_path_sample="$cross_platform_path/profiled-path-sample/$os"
if [ -e "$profiled_path_sample" ]; then
    cp "$profiled_path_sample" "$profiled_path/.path.sample"
fi
