alias coc='conda create -p .venv'
alias cor='conda env remove -p .venv'
alias coi='conda install -p .venv'
alias cocw='conda create -p "$WORKSPACE_CONFIG_DIR/venv"'
alias corw='conda env remove -p "$WORKSPACE_CONFIG_DIR/venv"'
alias coiw='conda install -p "$WORKSPACE_CONFIG_DIR/venv"'
