alias coc='conda create -p .venv'
alias cor='conda env remove -p .venv'
alias coi='conda install -p .venv'
alias coc@='conda create -p "$ATDIR/venv"'
alias cor@='conda env remove -p "$ATDIR/venv"'
alias coi@='conda install -p "$ATDIR/venv"'
