#!/bin/sh
set -eux

install_path="$1"

version='v0.11.5'

tar_file='nvim-linux-x86_64.tar.gz'
tar_url="https://github.com/neovim/neovim-releases/releases/download/$version/$tar_file"
tar_path="/tmp/$tar_file"

curl -fsSL -o "$tar_path" "$tar_url"

tar -xzf "$tar_path" -C "$install_path" --strip-components=1
