#!/bin/sh

set -eux

root="$(dirname "$(realpath "$0")")"
install_path="$1"

sudo apt install jq --yes --no-install-recommends
sudo apt install fzf --yes --no-install-recommends
sudo apt install pass --yes --no-install-recommends
sudo apt install rsync --yes --no-install-recommends

# TODO: Isolate rust installation if needed elsewhere
curl 'https://sh.rustup.rs' -sSf | sh -s -- -y --no-modify-path
ln -fs "$HOME/.cargo/bin/cargo" "$install_path/bin/"

echo 'Downloading and installing breadcrumbs...'
repo_path="$root/bin-submodules/breadcrumbs"
git submodule update --init "$repo_path"
# TODO: Wrap this behind a Makefile
cargo build --manifest-path="$repo_path/Cargo.toml" --release
cp "$repo_path/target/release/breadcrumbs" "$install_path/bin/"

echo 'Downloading and installing hburger...'
repo_path="$root/bin-submodules/hburger"
git submodule update --init "$repo_path"
# TODO: Wrap this behind a Makefile
cargo build --manifest-path="$repo_path/Cargo.toml" --release
cp "$repo_path/target/release/hburger" "$install_path/bin/"
