#!/bin/sh

set -eux

root="$(dirname "$(realpath "$0")")"
install_path="$1"

sudo apt install jq --yes --no-install-recommends
sudo apt install fzf --yes --no-install-recommends
sudo apt install make --yes --no-install-recommends
sudo apt install pass --yes --no-install-recommends
sudo apt install rsync --yes --no-install-recommends

# Docker
# Ref: https://docs.docker.com/engine/install/debian#install-using-the-repository
sudo apt install ca-certificates curl
sudo install -m 0755 -d /etc/apt/keyrings
sudo curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc
sudo chmod a+r /etc/apt/keyrings/docker.asc
sudo tee /etc/apt/sources.list.d/docker.sources <<EOF
Types: deb
URIs: https://download.docker.com/linux/debian
Suites: $(. /etc/os-release && echo "$VERSION_CODENAME")
Components: stable
Signed-By: /etc/apt/keyrings/docker.asc
EOF
sudo apt update
sudo apt install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin --no-install-recommends

# TODO: Isolate rust installation if needed elsewhere
curl 'https://sh.rustup.rs' -sSf | sh -s -- -y --no-modify-path
ln -fs "$HOME/.cargo/bin/cargo" "$install_path/bin/"

echo 'Downloading and installing breadcrumbs...'
repo_path="$root/bin-submodules/breadcrumbs"
git submodule update --init "$repo_path"
# TODO: Wrap this behind a Makefile
cargo build --manifest-path="$repo_path/Cargo.toml" --release
cp "$repo_path/target/release/breadcrumbs" "$install_path/bin/"

echo 'Downloading and installing hburger...'
repo_path="$root/bin-submodules/hburger"
git submodule update --init "$repo_path"
# TODO: Wrap this behind a Makefile
cargo build --manifest-path="$repo_path/Cargo.toml" --release
cp "$repo_path/target/release/hburger" "$install_path/bin/"
