#!/bin/sh

set -eux

root="$(dirname "$(realpath "$0")")"
install_path="$1"

sudo apt install --yes python3.11  # TODO: Check if downloading venv is necessary

tooling_venv_path="$HOME/.py-tooling-venv"
python3.11 -m venv "$tooling_venv_path"
# Ref: https://python-poetry.org/docs/#installing-manually
"$tooling_venv_path/bin/pip" install poetry==1.7.1
ln -s "$tooling_venv_path/bin/poetry" "$install_path/bin/"
# Ref: https://github.com/pappasam/jedi-language-server#installation
"$tooling_venv_path/bin/pip" install jedi-language-server==0.41.2
ln -s "$tooling_venv_path/bin/jedi-language-server" "$install_path/bin/"
# ---
ropify_path="$root/bin-submodules/ropify"
git submodule update --init "$ropify_path"
"$tooling_venv_path/bin/pip" install "$ropify_path"
ln -s "$tooling_venv_path/bin/ropify" "$install_path/bin/"

# Ref: https://docs.conda.io/projects/miniconda/en/latest/
conda_install_path="$HOME/.miniconda3"
conda_tmp_path='/tmp/miniconda.sh'
arch=$(uname -m)
conda_url="https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-$arch.sh"
wget "$conda_url" -O "$conda_tmp_path"
sh "$conda_tmp_path" -b -p "$conda_install_path"
rm "$conda_tmp_path"
ln -s "$conda_install_path/bin/conda" "$install_path/bin/"
