#!/bin/sh

set -eux

root="$(dirname "$(realpath "$0")")"
install_path="$1"

sudo apt install python3 python3-venv --yes --no-install-recommends

tooling_venv_path="$HOME/.py-tooling-venv"
python3 -m venv "$tooling_venv_path"
ropify_path="$root/bin-submodules/ropify"
git submodule update --init "$ropify_path"
"$tooling_venv_path/bin/pip" install "$ropify_path"
ln -s "$tooling_venv_path/bin/ropify" "$install_path/bin/"

# Ref: https://docs.astral.sh/uv/getting-started/installation
uv_version='0.9.18'
curl -LsSf "https://astral.sh/uv/$uv_version/install.sh" | sh

ty_version='0.0.7'
uv tool install "ty==$ty_version"
